### ISSUE TITLE
Operator crashes due to recurrent failed login attemps

### ISSUE THREAD

**Issue by aco-fwinzek** [MaibornWolff/hybrid-cloud-postgresql-operator#29]
# What happened?

It seems that the hybrid cloud operator pod repeatingly (once an hour) crashes during recurrent login attempts, see logs attached.

# Setup 
- Azure Kubernetes Service
- Azure Flexible Postgres Server backend

Any ideas how to get around this? Rotate the admin password? Or is this a bug in kopf implementation?

```
2024-12-10 15:11:13.445	[2024-12-10 14:11:13,445] kopf._core.engines.a [INFO    ] Initial authentication has finished.
2024-12-10 15:11:13.445	[2024-12-10 14:11:13,445] kopf.activities.auth [INFO    ] Activity 'login_via_client' succeeded.
2024-12-10 15:11:13.443	[2024-12-10 14:11:13,443] kopf._core.engines.a [INFO    ] Initial authentication has been initiated.
2024-12-10 15:11:13.442	[2024-12-10 14:11:13,442] kopf.activities.star [INFO    ] Activity 'configure' succeeded.
2024-12-10 15:11:09.394	kopf._cogs.structs.credentials.LoginError: Ran out of valid credentials. Consider installing an API client library or adding a login handler. See more: https://kopf.readthedocs.io/en/stable/authentication/
2024-12-10 15:11:09.394	    raise LoginError("Ran out of valid credentials. Consider installing "
2024-12-10 15:11:09.394	  File "/usr/local/lib/python3.10/site-packages/kopf/_cogs/structs/credentials.py", line 214, in select
2024-12-10 15:11:09.394	    yielded_key, yielded_item = self.select()
2024-12-10 15:11:09.394	  File "/usr/local/lib/python3.10/site-packages/kopf/_cogs/structs/credentials.py", line 195, in _items
2024-12-10 15:11:09.394	    async for key, item in self._items():
2024-12-10 15:11:09.394	  File "/usr/local/lib/python3.10/site-packages/kopf/_cogs/structs/credentials.py", line 158, in extended
2024-12-10 15:11:09.394	    async for key, info, context in vault.extended(APIContext, 'contexts'):
2024-12-10 15:11:09.394	  File "/usr/local/lib/python3.10/site-packages/kopf/_cogs/clients/auth.py", line 48, in wrapper
2024-12-10 15:11:09.394	    response = await request(
2024-12-10 15:11:09.394	  File "/usr/local/lib/python3.10/site-packages/kopf/_cogs/clients/api.py", line 200, in stream
2024-12-10 15:11:09.394	    async for raw_input in api.stream(
2024-12-10 15:11:09.394	  File "/usr/local/lib/python3.10/site-packages/kopf/_cogs/clients/watching.py", line 266, in watch_objs
2024-12-10 15:11:09.394	    async for raw_input in stream:
2024-12-10 15:11:09.394	  File "/usr/local/lib/python3.10/site-packages/kopf/_cogs/clients/watching.py", line 201, in continuous_watch
2024-12-10 15:11:09.394	    async for raw_event in stream:
2024-12-10 15:11:09.393	  File "/usr/local/lib/python3.10/site-packages/kopf/_cogs/clients/watching.py", line 86, in infinite_watch
2024-12-10 15:11:09.393	    async for raw_event in stream:
2024-12-10 15:11:09.393	  File "/usr/local/lib/python3.10/site-packages/kopf/_core/reactor/queueing.py", line 175, in watcher
2024-12-10 15:11:09.393	    await queueing.watcher(
2024-12-10 15:11:09.393	  File "/usr/local/lib/python3.10/site-packages/kopf/_core/reactor/observation.py", line 127, in resource_observer
2024-12-10 15:11:09.393	    await coro
2024-12-10 15:11:09.393	  File "/usr/local/lib/python3.10/site-packages/kopf/_cogs/aiokits/aiotasks.py", line 96, in guard
2024-12-10 15:11:09.393	    task.result()  # can raise the regular (non-cancellation) exceptions.
2024-12-10 15:11:09.393	  File "/usr/local/lib/python3.10/site-packages/kopf/_cogs/aiokits/aiotasks.py", line 226, in reraise
2024-12-10 15:11:09.393	    await aiotasks.reraise(root_done | root_cancelled | hung_done | hung_cancelled)
2024-12-10 15:11:09.393	  File "/usr/local/lib/python3.10/site-packages/kopf/_core/reactor/running.py", line 419, in run_tasks
2024-12-10 15:11:09.393	    await run_tasks(operator_tasks, ignored=existing_tasks)
2024-12-10 15:11:09.393	  File "/usr/local/lib/python3.10/site-packages/kopf/_core/reactor/running.py", line 138, in operator
2024-12-10 15:11:09.393	    return future.result()
2024-12-10 15:11:09.393	  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
2024-12-10 15:11:09.393	    return loop.run_until_complete(main)
2024-12-10 15:11:09.393	  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
2024-12-10 15:11:09.393	    asyncio.run(coro)
2024-12-10 15:11:09.393	  File "/usr/local/lib/python3.10/site-packages/kopf/_core/reactor/running.py", line 81, in run
2024-12-10 15:11:09.393	    return running.run(
2024-12-10 15:11:09.393	  File "/usr/local/lib/python3.10/site-packages/kopf/cli.py", line 109, in run
2024-12-10 15:11:09.393	    return __callback(*args, **kwargs)
2024-12-10 15:11:09.392	  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
2024-12-10 15:11:09.392	    return ctx.invoke(f, obj, *args, **kwargs)
2024-12-10 15:11:09.392	  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 92, in new_func
2024-12-10 15:11:09.392	    return fn(*args, **kwargs)
2024-12-10 15:11:09.392	  File "/usr/local/lib/python3.10/site-packages/kopf/cli.py", line 60, in wrapper
2024-12-10 15:11:09.392	    return __callback(*args, **kwargs)
2024-12-10 15:11:09.392	  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
2024-12-10 15:11:09.392	    return ctx.invoke(self.callback, **ctx.params)
2024-12-10 15:11:09.392	  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
2024-12-10 15:11:09.392	    return _process_result(sub_ctx.command.invoke(sub_ctx))
2024-12-10 15:11:09.391	  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
2024-12-10 15:11:09.391	    rv = self.invoke(ctx)
2024-12-10 15:11:09.391	  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
2024-12-10 15:11:09.391	    return self.main(*args, **kwargs)
2024-12-10 15:11:09.391	  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
2024-12-10 15:11:09.391	    sys.exit(main())
2024-12-10 15:11:09.391	  File "/usr/local/bin/kopf", line 8, in <module>
2024-12-10 15:11:09.391	Traceback (most recent call last):
2024-12-10 15:11:09.388	[2024-12-10 14:11:09,388] kopf.activities.auth [WARNING ] Activity 'login_via_client' is cancelled. Will escalate.
2024-12-10 15:11:09.388	kopf._cogs.structs.credentials.LoginError: Ran out of valid credentials. Consider installing an API client library or adding a login handler. See more: https://kopf.readthedocs.io/en/stable/authentication/
2024-12-10 15:11:09.388	    raise LoginError("Ran out of valid credentials. Consider installing "
2024-12-10 15:11:09.388	  File "/usr/local/lib/python3.10/site-packages/kopf/_cogs/structs/credentials.py", line 214, in select
2024-12-10 15:11:09.388	    yielded_key, yielded_item = self.select()
2024-12-10 15:11:09.388	  File "/usr/local/lib/python3.10/site-packages/kopf/_cogs/structs/credentials.py", line 195, in _items
2024-12-10 15:11:09.388	    async for key, item in self._items():
2024-12-10 15:11:09.388	  File "/usr/local/lib/python3.10/site-packages/kopf/_cogs/structs/credentials.py", line 158, in extended
2024-12-10 15:11:09.388	    async for key, info, context in vault.extended(APIContext, 'contexts'):
2024-12-10 15:11:09.388	  File "/usr/local/lib/python3.10/site-packages/kopf/_cogs/clients/auth.py", line 48, in wrapper
2024-12-10 15:11:09.388	    response = await request(
2024-12-10 15:11:09.388	  File "/usr/local/lib/python3.10/site-packages/kopf/_cogs/clients/api.py", line 200, in stream
2024-12-10 15:11:09.388	    async for raw_input in api.stream(
2024-12-10 15:11:09.388	  File "/usr/local/lib/python3.10/site-packages/kopf/_cogs/clients/watching.py", line 266, in watch_objs
2024-12-10 15:11:09.388	    async for raw_input in stream:
2024-12-10 15:11:09.388	  File "/usr/local/lib/python3.10/site-packages/kopf/_cogs/clients/watching.py", line 201, in continuous_watch
2024-12-10 15:11:09.388	    async for raw_event in stream:
2024-12-10 15:11:09.388	  File "/usr/local/lib/python3.10/site-packages/kopf/_cogs/clients/watching.py", line 86, in infinite_watch
2024-12-10 15:11:09.388	    async for raw_event in stream:
2024-12-10 15:11:09.388	  File "/usr/local/lib/python3.10/site-packages/kopf/_core/reactor/queueing.py", line 175, in watcher
2024-12-10 15:11:09.388	    await queueing.watcher(
2024-12-10 15:11:09.388	  File "/usr/local/lib/python3.10/site-packages/kopf/_core/reactor/observation.py", line 127, in resource_observer
2024-12-10 15:11:09.388	    await coro
2024-12-10 15:11:09.388	  File "/usr/local/lib/python3.10/site-packages/kopf/_cogs/aiokits/aiotasks.py", line 96, in guard
2024-12-10 15:11:09.388	Traceback (most recent call last):
2024-12-10 15:11:09.388	[2024-12-10 14:11:09,386] kopf._core.reactor.r [ERROR   ] Resource observer has failed: Ran out of valid credentials. Consider installing an API client library or adding a login handler. See more: https://kopf.readthedocs.io/en/stable/authentication/
2024-12-10 15:11:09.385	[2024-12-10 14:11:09,384] kopf._core.engines.a [INFO    ] Re-authentication has been initiated.
```

**Comment by swoehrl-mw** [comment]
Hi @aco-fwinzek. That is very strange behaviour. The operator utilizes the automatically provided token of its Kubernetes serviceaccount. That token should be valid for the entire lifetime of the pod.
Do you perchance have changed any Kubernetes cluster configuration that could affect this?

**Comment by aco-fwinzek** [comment]
I dido some research, but I could not really find a configuration change that hints at this problem here. I also recreated the Azure Managed Identity and the Service Account but that did not work out. The 
azure-identity-token also looked valid to me.

**Comment by aco-fwinzek** [comment]
From AKS docs, I just found a release note that makes me curious.

> Starting 1.30 Kubernetes version, apiserver will have --service-account-extend-token-expiration set to false on [OIDC issuer](https://learn.microsoft.com/en-us/azure/aks/use-oidc-issuer) enabled clusters. In versions prior to 1.30, service account tokens injected into pods were given an extended lifetime so they remain valid even after a new refreshed token is provided. Prior to upgrading to 1.30, the metric serviceaccount_stale_tokens_total and the audit annotation authentication.k8s.io/stale-token can be used to monitor for workloads that depend on the extended lifetime and are continuing to use tokens even after a refreshed token is provided to the container. If no action is taken, workloads depending on the extended lifetime will break once the cluster is upgraded to 1.30. See [reference](https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/1205-bound-service-account-tokens/README.md) for details.

Source: https://github.com/Azure/AKS/releases/tag/2024-06-09

And this is what we actually did, upgrading the cluster. Could this be the problem?

Edit: Now I found an issue exactly relating to this here, in the kopf implementation. https://github.com/nolar/kopf/issues/980

Dunno, if that is the original source of the problem...

**Comment by swoehrl-mw** [comment]
Hi @aco-fwinzek. The token expiration period sounds like the culprit. The issue you linked looks similar. Do you also have `Session is closed` reports in the logs like there?
I did a quick test and ran the operator on a local k3d cluster with token-expiration enabled. But there kopf was able to renew authentication after one hour without problems. So my guess is that this is an AKS special behaviour. I'll try to debug on an AKS cluster, but in the end we might need to wait for a fix from kopf.

**Comment by aco-fwinzek** [comment]
@swoehrl-mw No, I again checked the logs carefully and couldn't find a `Session is closed` report. Do you have something to report? By any chance, have you been able to reproduce it?

**Comment by swoehrl-mw** [comment]
> Do you have something to report? By any chance, have you been able to reproduce it?

Sorry, I didn't yet get around to it.

**Comment by swoehrl-mw** [comment]
Hi @aco-fwinzek. I managed to reproduce the problem on an AKS cluster (version 1.31.2).
This is definitly a problem with kopf. I tried the draft PR from the linked issue and also some other modifications but it didn't solve the problem (sometimes only made it worse).

But I found a workaround that at least for me stops the restarts and auth problems. Using the token from a projected volume it seems to not suffer from the same problem. I've modified the operator accordingly and pushed that as a dev image.
Can you try it with your setup?

Simply add the following to the values for the hybrid-cloud-postgresql-operator helm chart (in the HelmRelease if you are using FluxCD):

```yaml
volumes:
  - name: satoken
    projected:
      sources:
      - serviceAccountToken:
          path: token
          expirationSeconds: 7200
volumeMounts:
  - mountPath: /var/run/secrets/serviceaccount/
    name: satoken

extraEnv:
  - name: TOKEN_PATH
    value: /var/run/secrets/serviceaccount/token

image:
  tag: "0.5.7-dev0"
```

If it works for you as well, I will clean it up, document it and create an official release with it.

**Comment by aco-fwinzek** [comment]
Hi @swoehrl-mw
That sounds like a plan, I'll try out this one and give you feedback asap.

**Comment by aco-fwinzek** [comment]
Hi @swoehrl-mw 

this is the behavior now using your suggestion. The crashes are ongoing after each re-login attempt. I did not change anything rather than your proposed changes. Do I need to remove the old service account or smth else?

```
  |   | 2025-01-14 07:44:26.721 | [2025-01-14 06:44:26,721] kopf._core.engines.a [INFO    ] Initial authentication has finished. |  
  |   | 2025-01-14 07:44:26.721 | [2025-01-14 06:44:26,721] kopf.activities.auth [INFO    ] Activity 'login_fn' succeeded. |  
  |   | 2025-01-14 07:44:26.720 | binascii.Error: Incorrect padding |  
  |   | 2025-01-14 07:44:26.720 | return binascii.a2b_base64(s) |  
  |   | 2025-01-14 07:44:26.720 | File "/usr/local/lib/python3.10/base64.py", line 87, in b64decode |  
  |   | 2025-01-14 07:44:26.720 | payload = base64.b64decode(payload) |  
  |   | 2025-01-14 07:44:26.720 | File "/operator/hybridcloud/operator.py", line 52, in login_fn |  
  |   | 2025-01-14 07:44:26.720 | Traceback (most recent call last): |  
  |   | 2025-01-14 07:44:26.720 | [2025-01-14 06:44:26,719] root                 [ERROR   ] Failed to use token. Falling back to normal kube-client authentication |  
  |   | 2025-01-14 07:44:26.719 | [2025-01-14 06:44:26,719] root                 [INFO    ] Using token from /var/run/secrets/serviceaccount/token for authentication |  
  |   | 2025-01-14 07:44:26.718 | [2025-01-14 06:44:26,718] kopf._core.engines.a [INFO    ] Initial authentication has been initiated. |  
  |   | 2025-01-14 07:44:26.717 | [2025-01-14 06:44:26,717] kopf.activities.star [INFO    ] Activity 'configure' succeeded. |  
  |   | 2025-01-14 07:44:22.803 | kopf._cogs.structs.credentials.LoginError: Ran out of valid credentials. Consider installing an API client library or adding a login handler. See more: https://kopf.readthedocs.io/en/stable/authentication/ |  
  |   | 2025-01-14 07:44:22.803 | raise LoginError("Ran out of valid credentials. Consider installing " |  
  |   | 2025-01-14 07:44:22.803 | File "/usr/local/lib/python3.10/site-packages/kopf/_cogs/structs/credentials.py", line 214, in select |  
  |   | 2025-01-14 07:44:22.803 | yielded_key, yielded_item = self.select() |  
  |   | 2025-01-14 07:44:22.803 | File "/usr/local/lib/python3.10/site-packages/kopf/_cogs/structs/credentials.py", line 195, in _items |  
  |   | 2025-01-14 07:44:22.803 | async for key, item in self._items(): |  
  |   | 2025-01-14 07:44:22.803 | File "/usr/local/lib/python3.10/site-packages/kopf/_cogs/structs/credentials.py", line 158, in extended |  
  |   | 2025-01-14 07:44:22.803 | async for key, info, context in vault.extended(APIContext, 'contexts'): |  
  |   | 2025-01-14 07:44:22.803 | File "/usr/local/lib/python3.10/site-packages/kopf/_cogs/clients/auth.py", line 48, in wrapper |  
  |   | 2025-01-14 07:44:22.803 | response = await request( |  
  |   | 2025-01-14 07:44:22.803 | File "/usr/local/lib/python3.10/site-packages/kopf/_cogs/clients/api.py", line 200, in stream |  
  |   | 2025-01-14 07:44:22.803 | async for raw_input in api.stream( |  
  |   | 2025-01-14 07:44:22.803 | File "/usr/local/lib/python3.10/site-packages/kopf/_cogs/clients/watching.py", line 266, in watch_objs |  
  |   | 2025-01-14 07:44:22.803 | async for raw_input in stream: |  
  |   | 2025-01-14 07:44:22.802 | File "/usr/local/lib/python3.10/site-packages/kopf/_cogs/clients/watching.py", line 201, in continuous_watch |  
  |   | 2025-01-14 07:44:22.802 | async for raw_event in stream: |  
  |   | 2025-01-14 07:44:22.802 | File "/usr/local/lib/python3.10/site-packages/kopf/_cogs/clients/watching.py", line 86, in infinite_watch |  
  |   | 2025-01-14 07:44:22.802 | async for raw_event in stream: |  
  |   | 2025-01-14 07:44:22.802 | File "/usr/local/lib/python3.10/site-packages/kopf/_core/reactor/queueing.py", line 175, in watcher |  
  |   | 2025-01-14 07:44:22.802 | await queueing.watcher( |  
  |   | 2025-01-14 07:44:22.802 | File "/usr/local/lib/python3.10/site-packages/kopf/_core/reactor/observation.py", line 127, in resource_observer |  
  |   | 2025-01-14 07:44:22.802 | await coro |  
  |   | 2025-01-14 07:44:22.802 | File "/usr/local/lib/python3.10/site-packages/kopf/_cogs/aiokits/aiotasks.py", line 96, in guard |  
  |   | 2025-01-14 07:44:22.802 | task.result()  # can raise the regular (non-cancellation) exceptions. |  
  |   | 2025-01-14 07:44:22.802 | File "/usr/local/lib/python3.10/site-packages/kopf/_cogs/aiokits/aiotasks.py", line 226, in reraise |  
  |   | 2025-01-14 07:44:22.802 | await aiotasks.reraise(root_done \| root_cancelled \| hung_done \| hung_cancelled) |  
  |   | 2025-01-14 07:44:22.802 | File "/usr/local/lib/python3.10/site-packages/kopf/_core/reactor/running.py", line 419, in run_tasks |  
  |   | 2025-01-14 07:44:22.802 | await run_tasks(operator_tasks, ignored=existing_tasks) |  
  |   | 2025-01-14 07:44:22.802 | File "/usr/local/lib/python3.10/site-packages/kopf/_core/reactor/running.py", line 138, in operator |  
  |   | 2025-01-14 07:44:22.802 | return future.result() |  
  |   | 2025-01-14 07:44:22.802 | File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete |  
  |   | 2025-01-14 07:44:22.802 | return loop.run_until_complete(main) |  
  |   | 2025-01-14 07:44:22.802 | File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run |  
  |   | 2025-01-14 07:44:22.802 | asyncio.run(coro) |  
  |   | 2025-01-14 07:44:22.802 | File "/usr/local/lib/python3.10/site-packages/kopf/_core/reactor/running.py", line 81, in run |  
  |   | 2025-01-14 07:44:22.802 | return running.run( |  
  |   | 2025-01-14 07:44:22.801 | File "/usr/local/lib/python3.10/site-packages/kopf/cli.py", line 109, in run |  
  |   | 2025-01-14 07:44:22.801 | return __callback(*args, **kwargs) |  
  |   | 2025-01-14 07:44:22.801 | File "/usr/local/lib/python3.10/site-packages/click/core.py", line 788, in invoke |  
  |   | 2025-01-14 07:44:22.801 | return ctx.invoke(f, obj, *args, **kwargs) |  
  |   | 2025-01-14 07:44:22.801 | File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 92, in new_func |  
  |   | 2025-01-14 07:44:22.801 | return fn(*args, **kwargs) |  
  |   | 2025-01-14 07:44:22.801 | File "/usr/local/lib/python3.10/site-packages/kopf/cli.py", line 60, in wrapper |  
  |   | 2025-01-14 07:44:22.801 | return __callback(*args, **kwargs) |  
  |   | 2025-01-14 07:44:22.801 | File "/usr/local/lib/python3.10/site-packages/click/core.py", line 788, in invoke |  
  |   | 2025-01-14 07:44:22.801 | return ctx.invoke(self.callback, **ctx.params) |  
  |   | 2025-01-14 07:44:22.801 | File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1443, in invoke |  
  |   | 2025-01-14 07:44:22.801 | return _process_result(sub_ctx.command.invoke(sub_ctx)) |  
  |   | 2025-01-14 07:44:22.800 | File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1697, in invoke |  
  |   | 2025-01-14 07:44:22.800 | rv = self.invoke(ctx) |  
  |   | 2025-01-14 07:44:22.800 | File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1082, in main |  
  |   | 2025-01-14 07:44:22.800 | return self.main(*args, **kwargs) |  
  |   | 2025-01-14 07:44:22.800 | File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1161, in __call__ |  
  |   | 2025-01-14 07:44:22.800 | sys.exit(main()) |  
  |   | 2025-01-14 07:44:22.800 | File "/usr/local/bin/kopf", line 8, in <module> |  
  |   | 2025-01-14 07:44:22.800 | Traceback (most recent call last): |  
  |   | 2025-01-14 07:44:22.798 | [2025-01-14 06:44:22,798] kopf.activities.auth [WARNING ] Activity 'login_fn' is cancelled. Will escalate. |  
  |   | 2025-01-14 07:44:22.795 | binascii.Error: Incorrect padding |  
  |   | 2025-01-14 07:44:22.795 | return binascii.a2b_base64(s) |  
  |   | 2025-01-14 07:44:22.795 | File "/usr/local/lib/python3.10/base64.py", line 87, in b64decode |  
  |   | 2025-01-14 07:44:22.795 | payload = base64.b64decode(payload) |  
  |   | 2025-01-14 07:44:22.795 | File "/operator/hybridcloud/operator.py", line 52, in login_fn |  
  |   | 2025-01-14 07:44:22.795 | Traceback (most recent call last): |  
  |   | 2025-01-14 07:44:22.795 | [2025-01-14 06:44:22,794] root                 [ERROR   ] Failed to use token. Falling back to normal kube-client authentication |  
  |   | 2025-01-14 07:44:22.795 | kopf._cogs.structs.credentials.LoginError: Ran out of valid credentials. Consider installing an API client library or adding a login handler. See more: https://kopf.readthedocs.io/en/stable/authentication/ |  
  |   | 2025-01-14 07:44:22.795 | raise LoginError("Ran out of valid credentials. Consider installing " |  
  |   | 2025-01-14 07:44:22.795 | File "/usr/local/lib/python3.10/site-packages/kopf/_cogs/structs/credentials.py", line 214, in select |  
  |   | 2025-01-14 07:44:22.795 | yielded_key, yielded_item = self.select() |  
  |   | 2025-01-14 07:44:22.795 | File "/usr/local/lib/python3.10/site-packages/kopf/_cogs/structs/credentials.py", line 195, in _items |  
  |   | 2025-01-14 07:44:22.795 | async for key, item in self._items(): |  
  |   | 2025-01-14 07:44:22.795 | File "/usr/local/lib/python3.10/site-packages/kopf/_cogs/structs/credentials.py", line 158, in extended |  
  |   | 2025-01-14 07:44:22.795 | async for key, info, context in vault.extended(APIContext, 'contexts'): |  
  |   | 2025-01-14 07:44:22.795 | File "/usr/local/lib/python3.10/site-packages/kopf/_cogs/clients/auth.py", line 48, in wrapper |  
  |   | 2025-01-14 07:44:22.795 | response = await request( |  
  |   | 2025-01-14 07:44:22.795 | File "/usr/local/lib/python3.10/site-packages/kopf/_cogs/clients/api.py", line 200, in stream |  
  |   | 2025-01-14 07:44:22.795 | async for raw_input in api.stream( |  
  |   | 2025-01-14 07:44:22.795 | File "/usr/local/lib/python3.10/site-packages/kopf/_cogs/clients/watching.py", line 266, in watch_objs |  
  |   | 2025-01-14 07:44:22.795 | async for raw_input in stream: |  
  |   | 2025-01-14 07:44:22.795 | File "/usr/local/lib/python3.10/site-packages/kopf/_cogs/clients/watching.py", line 201, in continuous_watch |  
  |   | 2025-01-14 07:44:22.795 | async for raw_event in stream: |  
  |   | 2025-01-14 07:44:22.795 | File "/usr/local/lib/python3.10/site-packages/kopf/_cogs/clients/watching.py", line 86, in infinite_watch |  
  |   | 2025-01-14 07:44:22.795 | async for raw_event in stream: |  
  |   | 2025-01-14 07:44:22.795 | File "/usr/local/lib/python3.10/site-packages/kopf/_core/reactor/queueing.py", line 175, in watcher |  
  |   | 2025-01-14 07:44:22.795 | await queueing.watcher( |  
  |   | 2025-01-14 07:44:22.795 | File "/usr/local/lib/python3.10/site-packages/kopf/_core/reactor/observation.py", line 127, in resource_observer |  
  |   | 2025-01-14 07:44:22.795 | await coro |  
  |   | 2025-01-14 07:44:22.795 | File "/usr/local/lib/python3.10/site-packages/kopf/_cogs/aiokits/aiotasks.py", line 96, in guard |  
  |   | 2025-01-14 07:44:22.795 | Traceback (most recent call last): |  
  |   | 2025-01-14 07:44:22.795 | [2025-01-14 06:44:22,794] kopf._core.reactor.r [ERROR   ] Resource observer has failed: Ran out of valid credentials. Consider installing an API client library or adding a login handler. See more: https://kopf.readthedocs.io/en/stable/authentication/ |  
  |   | 2025-01-14 07:44:22.793 | [2025-01-14 06:44:22,793] root                 [INFO    ] Using token from /var/run/secrets/serviceaccount/token for authentication |  
  |   | 2025-01-14 07:44:22.793 | [2025-01-14 06:44:22,792] kopf._core.engines.a [INFO    ] Re-authentication has been initiated.


```

**Comment by swoehrl-mw** [comment]
The updated workaround is now part of the newest release (v0.5.7) and can be enabled via the helm values.
